apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: livebus-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: livebus-route
spec:
  parentRefs:
    - name: livebus-gateway
  rules:
    - backendRefs:
        - name: livebus-app
          port: 80
