apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: livebus-secret-provider
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/delta-heading-455916-c2/secrets/db-name/versions/latest"
        path: "database-name"
      - resourceName: "projects/delta-heading-455916-c2/secrets/db-user/versions/latest"
        path: "database-user"
      - resourceName: "projects/delta-heading-455916-c2/secrets/db-password/versions/latest"
        path: "database-password"
      - resourceName: "projects/delta-heading-455916-c2/secrets/rabbitmq-user/versions/latest"
        path: "rabbitmq-user"
      - resourceName: "projects/delta-heading-455916-c2/secrets/rabbitmq-password/versions/latest"
        path: "rabbitmq-password"
  secretObjects:
    - secretName: livebus-db-secrets
      type: Opaque
      data:
        - objectName: database-name
          key: database-name
        - objectName: database-user
          key: database-user
        - objectName: database-password
          key: database-password
        - objectName: rabbitmq-user
          key: rabbitmq-user
        - objectName: rabbitmq-password
          key: rabbitmq-password
