apiVersion: v1
kind: ServiceAccount
metadata:
  name: livebus-reader-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: livebus-secret-reader@delta-heading-455916-c2.iam.gserviceaccount.com
